### PR TITLE
Logarithmic ticks/subticks

### PR DESCRIPTION
**Pull request by danielbolan**
Hello,

Sorry for the delay, I decided to take a second shot at it with some refactoring. I hope it'll be cleaner to review this way. Unfortunately I screwed up the branch and it ended up closing the previous PR #22 , so I'm opening this one up now.

It incorporates both my use case for exponential scales and the logarithmic scales requested in #14.

screenshot

Please don't hesitate to ask if there's anything else that'd be helpful!

### CODE REVIEW

**Comment by leechwort** [comment]
Great, I'll take a look in a while!

**Comment by leechwort** [comment]
Hi @danielbolan ! I've checked your PR on my side, works ok when I use logarithmic subticks or both ticks and subticks. But looks like there are no changes between "log ticks + log subticks" and "log ticks only" modes:
ticks-subticks
ticks-only

Can you check this on your side?

**Comment by danielbolan** [comment]
Hi, thanks for checking it out! Yes, this is intentional, as I'm not sure what it'd represent mathematically. I tried checking out whether I could disable the subtick checkbox when the ticks checkbox is checked but all I found was [inkex.gui.app](https://inkscape.gitlab.io/extensions/documentation/source/inkex.gui.app.html) and didn't much want to write a GTK app for it. Maybe this is something better done in documentation?

I could also just go ahead and implement the combination of both log tick+subticks but I don't think it'll get used and will complicate the code a bit.

**Comment by leechwort** [comment]
@danielbolan Ok, good! Let's say it will be in the issue list:) Merging! Thank you very much for your contribution!:)

**Pull request merged**
